# Generated by Django 5.0.3 on 2024-03-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
